# Site settings
port: 4000
highlighter: pygments
title: JRubyArt (Code as Art)
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  JRubyArt is a ruby wrapper for processing-3.0.  Create processing sketches 
  in ruby using regular ruby-2.1 syntax, and use the magic JRuby to run them.
  You can use both rubygems and and regular processing libraries in your 
  sketches. Features run, watch and live modes (uses pry).
baseurl: "" # the subpath of your site, e.g. /blog/
urls:
  bugs: http://github.com/ruby-processing/jruby_art/issues
  wiki: https://github.com/ruby-processing/JRubyArt/wiki
  github: https://github.com/ruby-processing/jruby_art
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

