# Site settings
port: 4000
title: The Ruby-Processing Group Site
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This the home for the ruby-processing group.
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
urls:
  bugs: http://github.com/ruby-processing/jruby_art/issues
  wiki: https://github.com/ruby-processing/JRubyArt/wiki
  github: https://github.com/ruby-processing/jruby_art
twitter_username: monkstoneT
github_username:  monkstone
collections:
  welcome:
    output: true
    permalink: /welcome/:path/
  projects:
      output: true
      permalink: /projects/:path/  
  hype:
    output: true
    permalink: /hype/:path/
syntax-highlighting:
  enabled: true
  css: syntax.css
# Build settings
kramdown:
  syntax_highlighter: rouge
  input: GFM
gems:
  - jekyll-sitemap
  - kramdown
  - rouge
