# Site settings
port: 4000
highlighter: pygments
title: JRubyArt (Code as Art)
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  JRubyArt is a ruby wrapper for processing-3.0. For processing-2.0, use
  ruby-processing.
baseurl: "" # the subpath of your site, e.g. /blog/
urls:
  bugs: http://github.com/ruby-processing/jruby_art/issues
  wiki: https://github.com/ruby-processing/JRubyArt/wiki
  github: https://github.com/ruby-processing/jruby_art
twitter_username: monkstoneT
github_username:  monkstone
syntax-highlighting:
  enabled: true
  css: syntax.css        

# Build settings
markdown: kramdown

